# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('testmodule', ['core'])
    module.source = [
        'model/testmodule.cc',
        'helper/testmodule-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('testmodule')
    module_test.source = [
        'test/testmodule-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'testmodule'
    headers.source = [
        'model/testmodule.h',
        'helper/testmodule-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

